In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
a=50
b=50
c=a+b
print(c)

100


In [ ]:
x="helo"
x

'helo'

In [ ]:
l1=[1,2,3,4,5]

In [ ]:
for x in l1:
  print(x)

1
2
3
4
5


In [ ]:
len(l1)

5

In [ ]:
l1.append(7)

In [ ]:
l1

[1, 2, 3, 4, 5, 7]

In [ ]:
l2=[8,9,10]

In [ ]:
l3=l1+l2
l3

[1, 2, 3, 4, 5, 7, 8, 9, 10]

In [ ]:
l1=[1,1,1,2,2,23,3,3,4,4]

In [ ]:
l2=[]
for x in l1:
  if x not in l2:
    l2.append(x)
l2

[1, 2, 23, 3, 4]

In [ ]:
l2=list(set(l1))
l2

[1, 2, 3, 4, 23]

In [ ]:
a=10
b=1.5
c='ojas'

print(type(a))
print(type(b))
print(type(c))


<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
for x in range (6):
  print(x)

0
1
2
3
4
5


In [ ]:
l1=[1,2,3,4,5,6,7,8]
print(l1[:4])

[1, 2, 3, 4]


In [ ]:
l1[-1]

8

In [ ]:
l1[::-1]

[8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
str1=input("Enter the name: ")
str2=str1[::-1]

if str1==str2:
  print("The string is palindrome")
else:
  print("It is not a palindrome")

Enter the name: happy
It is not a palindrome


In [ ]:
import random
numbers=[1,2,4,5,6,7,8]
random.shuffle(numbers)
print(numbers)

[2, 5, 1, 6, 4, 7, 8]


In [ ]:
days=["monday","tuesday","wednesday","thursday","friday"]
"wednesday" in days

True

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday"]
"wednesday" not in days

False

In [ ]:
list=["red","orage","pink","black"]
print(list)
list.clear()
print(list)

['red', 'orage', 'pink', 'black']
[]


In [ ]:
nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

[1, 2, 3, 4, 1, 4, 1, 7, 8, 1]


4

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
list=["red","orange","pink","black"]
print(list)
list.clear()
print(list)

['red', 'orange', 'pink', 'black']
[]


In [ ]:
nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

[1, 2, 3, 4, 1, 4, 1, 7, 8, 1]


4

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
A=[1,3,2,4,5]
B=[5,6,7,3,6]
print(A)
print(B)
A.extend(B)
print(A)

[1, 3, 2, 4, 5]
[5, 6, 7, 3, 6]
[1, 3, 2, 4, 5, 5, 6, 7, 3, 6]


In [ ]:
a=(5,)
print(a)
print(type(a))

(5,)
<class 'tuple'>


In [ ]:
a=(5)
type(a)

int

In [ ]:
a=(1,2,3,4,5)
print(a)

(1, 2, 3, 4, 5)


In [ ]:
b=(6,5,5,9,2,0)
print(b)

(6, 5, 5, 9, 2, 0)


In [ ]:
c=("one","two","three")
c

('one', 'two', 'three')

In [ ]:
("one","two","three")

('one', 'two', 'three')

In [ ]:
mix=("hello",708,66.8,1,2)
mix

('hello', 708, 66.8, 1, 2)

In [ ]:
a=(1,2,3,4,"hello")
print(a[4])

hello


In [ ]:
a={
    "name":"ojas",
    "age":23,
    "education":"engineer"
}
a

{'name': 'ojas', 'age': 23, 'education': 'engineer'}

In [ ]:
len(a)

3

In [ ]:
type(a)

dict

In [ ]:
x=a.keys
x

<function dict.keys>

In [ ]:
y=a.values()
y

dict_values(['ojas', 23, 'engineer'])

In [ ]:
z=a.items()
z

dict_items([('name', 'ojas'), ('age', 23), ('education', 'engineer')])

In [ ]:
set1={1,2,3,4}
print(set1)

{1, 2, 3, 4}


In [ ]:
set={1,2,3,4,5,6,7,1,1}
print(set)

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
def add():
    a=2
    b=3
    sum=a+b
    return sum
add()
print(add())

5


In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np

In [ ]:
A1=np.array([1,2,3,4])
print(A)

[1, 3, 2, 4, 5, 5, 6, 7, 3, 6]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(4,)

In [ ]:
A1.size

4

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
A2.size

8

In [ ]:
A2.shape

(2, 4)

In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(A3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
A3.shape

(1, 3, 4)

In [ ]:
A3.size

12

In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.ndim

3

In [ ]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.ndim

1

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
type(z3)

numpy.ndarray

In [ ]:
z3.size

24

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.ndim

3

In [ ]:
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [ ]:
a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a3=np.zeros((4,2,3),dtype=int)
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(4, 2, 3)

In [ ]:
a3.size

24

In [ ]:
a3.ndim

3

In [ ]:
import numpy as np
f1=np.full(3,9)
f1

array([9, 9, 9])

In [ ]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [ ]:
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
f3=np.full([4,2,3],10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])